"""Typed expression primitives for DuckPlus."""

# pylint: disable=duplicate-code

from .dependencies import ExpressionDependency
from .expression import (
    AliasedExpression,
    BlobExpression,
    BooleanExpression,
    CaseExpressionBuilder,
    DateExpression,
    GenericExpression,
    NumericAggregateFactory,
    NumericExpression,
    TemporalAggregateFactory,
    SelectStatementBuilder,
    TimestampExpression,
    TypedExpression,
    VarcharExpression,
)
from .ducktype import (
    Blob,
    Boolean,
    Date,
    Datetime,
    Double,
    Generic,
    Integer,
    Numeric,
    Smallint,
    Tinyint,
    Timestamp,
    Utinyint,
    Usmallint,
    Uinteger,
    Float,
    Varchar,
    ducktype,
    select,
)

__all__ = [
    "AliasedExpression",
    "BlobExpression",
    "BooleanExpression",
    "CaseExpressionBuilder",
    "DateExpression",
    "GenericExpression",
    "NumericAggregateFactory",
    "NumericExpression",
    "TemporalAggregateFactory",
    "SelectStatementBuilder",
    "TimestampExpression",
    "TypedExpression",
    "VarcharExpression",
    "ExpressionDependency",
    "ducktype",
    "Numeric",
    "Varchar",
    "Boolean",
    "Blob",
    "Generic",
    "Tinyint",
    "Smallint",
    "Integer",
    "Utinyint",
    "Usmallint",
    "Uinteger",
    "Float",
    "Double",
    "Date",
    "Datetime",
    "Timestamp",
    "select",
]
