"""Protocol describing the static surface for temporal expressions."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from .boolean import BooleanExprProto
from .numeric import NumericExprProto
from .string import StringExprProto


@runtime_checkable
class TemporalExprProto(Protocol):
    """Static interface for timestamp helpers generated by ``ExprMeta``."""

    def date_trunc(self, part: str) -> "TemporalExprProto":
        ...

    def extract(self, field: str) -> NumericExprProto:
        ...

    def strftime(self, fmt: str) -> StringExprProto:
        ...

    def between(self, lower: "TemporalExprProto", upper: "TemporalExprProto") -> BooleanExprProto:
        ...


__all__ = ["TemporalExprProto"]
