name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Sync dependencies
        run: uv sync

      - name: Run pytest
        run: uv run pytest

      - name: Run mypy
        run: uv run mypy src/duckplus

      - name: Run ty
        run: uvx ty check src/duckplus
